[[plugins]]
repo = 'thinca/vim-quickrun'
hook_post_update = '''
set splitright
let g:quickrun_config={'_': {'split': 'vertical'}}
'''
on_i = 1

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = ['python']

[[plugins]]
repo = 'Shougo/neocomplete.vim'
on_i = 1
