#------------------------------------------------------------------------------------------------------------
# Plugin manager:


[[plugins]]
repo = 'Shougo/dein.vim'


#------------------------------------------------------------------------------------------------------------
# Appearance:


[[plugins]]
repo = 'flazz/vim-colorschemes'
hook_add = '''
	syntax on
	" colorscheme molokai
	colorscheme Tomorrow-Night
	" colorscheme Tomorrow-Night-Bright
	" colorscheme zenburn
	" colorscheme onedark
	" colorscheme badwolf
	" colorscheme gruvbox
	set t_Co=256
'''


# git clone https://github.com/powerline/fonts.git --depth=1
# cd fonts
# ./install.sh
# Use : Source Code Pro for Powerline semibold (size:11)
[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
	let g:airline#extensions#tabline#enabled = 1
	let g:airline#extensions#tabline#left_sep = ' '
	let g:airline#extensions#tabline#left_alt_sep = '|'
	let g:airline#extensions#tabline#formatter = 'default'
	nmap <C-n> <Plug>AirlineSelectPrevTab
	nmap <C-p> <Plug>AirlineSelectNextTab
'''


[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
	let g:airline_theme = 'murmur'
'''


#------------------------------------------------------------------------------------------------------------
# Completion, Syntax:


[[plugins]]
repo = 'ujihisa/neco-look'
hook_add = '''
	let g:neocomplete#text_mode_filetypes = { "_" : 1 }
'''


[[plugins]]
repo = 'cespare/vim-toml'


#------------------------------------------------------------------------------------------------------------
# Others:


[[plugins]]
repo = 'tpope/vim-fugitive'


[[plugins]]
repo = 'rhysd/accelerated-jk'
hook_add = '''
	nmap j <Plug>(accelerated_jk_gj)
	nmap k <Plug>(accelerated_jk_gk)
'''
